### ISSUE TITLE
Options page remains blank

### ISSUE THREAD

**Issue by yfdyh000** [code-charity/unlock-keyboard-and-mouse#7]
```
chrome-extension://ijngdimmjkngoglcjaheoadciaalbafl/_locales/zh-CN/messages.json
Failed to load resource: net::ERR_FILE_NOT_FOUND
satus.js:1084 LOCALE: data was successfully imported
```

**Comment by yfdyh000** [comment]
`window.navigator.language` says 'zh-CN', `-` should be replaced. It will still fail if the user uses a language variant, e.g. en-GB.

I recommend use the https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/getMessage.

**Comment by ghost** [comment]
Will be fixed.

`getMessage` does not allow the user to change the language if he wants to.

**Comment by yfdyh000** [comment]
Another issue:
Error handling response: TypeError: Failed to construct 'URL': Invalid URL
    at chrome-extension://abppclkffjbjdnidkcifojofhikihmmd/options-page/index.js:38:11

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs To access Tab.url, Tab.title, and Tab.favIconUrl (or to filter by these properties via tabs.query()), you need to have the "tabs" permission, or have host permissions that match Tab.url.

**Comment by ghost** [comment]
https://github.com/victor-savinov/unlock-keyboard-and-mouse/releases/tag/v2.1
